#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';

function run(command) {
  console.log(`\n> ${command}`);
  execSync(command, { stdio: 'inherit' });
}

function output(command) {
  return execSync(command, { encoding: 'utf8' });
}

try {
  run('supabase start');

  const status = output('supabase status -o env');
  const values = {};
  for (const line of status.split(/\r?\n/)) {
    const match = line.match(/^([A-Z_]+)=(.*)$/);
    if (match) values[match[1]] = match[2].replace(/^"|"$/g, '');
  }

  const required = ['API_URL', 'ANON_KEY', 'SERVICE_ROLE_KEY'];
  for (const key of required) {
    if (!values[key]) throw new Error(`Supabase did not return ${key}`);
  }

  mkdirSync('apps/web', { recursive: true });
  const env = [
    '# Generated by npm run setup:local — do not commit this file.',
    `NEXT_PUBLIC_SUPABASE_URL=${values.API_URL}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${values.ANON_KEY}`,
    `SUPABASE_SERVICE_ROLE_KEY=${values.SERVICE_ROLE_KEY}`,
    'NEXT_PUBLIC_APP_URL=http://localhost:3000',
    '',
  ].join('\n');
  writeFileSync('apps/web/.env.local', env);
  console.log('Created apps/web/.env.local with local Supabase credentials.');

  run('supabase db reset');
  console.log('\nLocal Cloud POS setup is complete. Start the app with: npm run dev');
} catch (error) {
  console.error('\nLocal setup failed.');
  console.error('Make sure Docker Desktop is running, then try: npm run setup:local');
  process.exit(error?.status || 1);
}
